#pragma once
#include <SSD1322.h>

// ============================================================================
//  BigDigits - clean condensed 16px numeric font ("Option 1c") for the PSU
//  main-readout big numbers. Covers '0'-'9', '.', '-', ' '. Digits are
//  monospace so tabular values stay column-aligned; '.'/'-'/' ' are narrower.
//  Generated by tools/bigfont.py - edit the glyph art there, not here,
//  then re-run: python tools/bigfont.py  (writes src/BigDigits.h).
//
//  Each glyph is HEIGHT rows; row bit c (LSB = leftmost column) is ink.
//  Draw left-anchored at the glyph-cell TOP row; the ink baseline is row
//  BASELINE, so place text with yTop = baselineY - BigDigits::BASELINE.
// ============================================================================
namespace BigDigits {
static const int HEIGHT   = 16;
static const int BASELINE = 15;  // bottom ink row within the cell

static const uint16_t D0[16] = { 0x00F8, 0x01FC, 0x038E, 0x0306, 0x0707, 0x0707, 0x0707, 0x0707, 0x0707, 0x0707, 0x0707, 0x0707, 0x0306, 0x038E, 0x01FC, 0x00F8 };
static const uint16_t D1[16] = { 0x0070, 0x0078, 0x007C, 0x0076, 0x0073, 0x0070, 0x0070, 0x0070, 0x0070, 0x0070, 0x0070, 0x0070, 0x0070, 0x01FC, 0x01FC, 0x01FC };
static const uint16_t D2[16] = { 0x00FC, 0x01FE, 0x0383, 0x0703, 0x0700, 0x0380, 0x01C0, 0x00E0, 0x0070, 0x0038, 0x001C, 0x000E, 0x0007, 0x03FF, 0x03FF, 0x03FF };
static const uint16_t D3[16] = { 0x01FE, 0x01FE, 0x01C0, 0x01C0, 0x01C0, 0x01E0, 0x00FC, 0x00FC, 0x01E0, 0x01C0, 0x01C0, 0x01C0, 0x0383, 0x01C7, 0x01FE, 0x00FC };
static const uint16_t D4[16] = { 0x01C0, 0x01E0, 0x01B0, 0x0198, 0x018C, 0x0186, 0x0183, 0x03FF, 0x03FF, 0x0180, 0x0180, 0x0180, 0x0180, 0x0180, 0x0180, 0x0180 };
static const uint16_t D5[16] = { 0x03FE, 0x03FE, 0x0006, 0x0006, 0x0006, 0x00FE, 0x01FE, 0x01C0, 0x0380, 0x0380, 0x0380, 0x0380, 0x0383, 0x01C7, 0x01FE, 0x00FC };
static const uint16_t D6[16] = { 0x01F8, 0x03FC, 0x000E, 0x0006, 0x0007, 0x0007, 0x00F7, 0x03FF, 0x038F, 0x0707, 0x0707, 0x0707, 0x0306, 0x038E, 0x01FC, 0x00F8 };
static const uint16_t D7[16] = { 0x03FF, 0x03FF, 0x03FF, 0x0380, 0x01C0, 0x01C0, 0x00E0, 0x00E0, 0x0070, 0x0070, 0x0038, 0x0038, 0x001C, 0x001C, 0x000E, 0x000E };
static const uint16_t D8[16] = { 0x00FC, 0x01FE, 0x0387, 0x0303, 0x0303, 0x01CE, 0x00FC, 0x00FC, 0x01CE, 0x0387, 0x0303, 0x0303, 0x0303, 0x0387, 0x01FE, 0x00FC };
static const uint16_t D9[16] = { 0x00F8, 0x01FC, 0x038E, 0x0707, 0x0707, 0x0707, 0x078E, 0x03FC, 0x0380, 0x0380, 0x01C0, 0x01C0, 0x00E0, 0x00E0, 0x0070, 0x0038 };
static const uint16_t DOT[16] = { 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0006, 0x0007, 0x0007, 0x0006 };
static const uint16_t DASH[16] = { 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x00FC, 0x00FC, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000 };
static const uint16_t SPACE[16] = { 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000 };

struct Glyph { uint8_t width; uint8_t advance; const uint16_t* rows; };

// Look up a glyph by character; unsupported chars fall back to a blank space.
inline Glyph glyphFor(char ch) {
    if (ch == '0') return { 11, 12, D0 };
    if (ch == '1') return { 11, 12, D1 };
    if (ch == '2') return { 11, 12, D2 };
    if (ch == '3') return { 11, 12, D3 };
    if (ch == '4') return { 11, 12, D4 };
    if (ch == '5') return { 11, 12, D5 };
    if (ch == '6') return { 11, 12, D6 };
    if (ch == '7') return { 11, 12, D7 };
    if (ch == '8') return { 11, 12, D8 };
    if (ch == '9') return { 11, 12, D9 };
    if (ch == '.') return { 4, 5, DOT };
    if (ch == '-') return { 11, 12, DASH };
    if (ch == ' ') return { 6, 6, SPACE };
    return { 6, 6, SPACE };
}

// Total advance width in pixels of string s (for right-alignment).
inline int textWidth(const char* s) {
    int w = 0;
    for (; *s; ++s) w += glyphFor(*s).advance;
    return w;
}

// Draw s left-anchored with its cell top at (x, yTop) in the given grey level.
inline void draw(SSD1322& d, int x, int yTop, const char* s, uint8_t color) {
    for (; *s; ++s) {
        Glyph g = glyphFor(*s);
        for (int r = 0; r < HEIGHT; ++r) {
            uint16_t bits = g.rows[r];
            for (int c = 0; c < g.width; ++c)
                if (bits & (1u << c)) d.setPixel(x + c, yTop + r, color);
        }
        x += g.advance;
    }
}

// Draw s right-anchored so its rightmost advance column sits at x=rightX.
inline void drawRight(SSD1322& d, int rightX, int yTop, const char* s, uint8_t color) {
    draw(d, rightX + 1 - textWidth(s), yTop, s, color);
}

}  // namespace BigDigits
