// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------------ //
// quadrature_encoder //
// ------------------ //

#define quadrature_encoder_wrap_target 17
#define quadrature_encoder_wrap 22
#define quadrature_encoder_pio_version 0

static const uint16_t quadrature_encoder_program_instructions[] = {
    0x0011, //  0: jmp    17
    0x0010, //  1: jmp    16
    0x0017, //  2: jmp    23
    0x0011, //  3: jmp    17
    0x0017, //  4: jmp    23
    0x0011, //  5: jmp    17
    0x0011, //  6: jmp    17
    0x0010, //  7: jmp    16
    0x0010, //  8: jmp    16
    0x0011, //  9: jmp    17
    0x0011, // 10: jmp    17
    0x0017, // 11: jmp    23
    0x0011, // 12: jmp    17
    0x0017, // 13: jmp    23
    0x0010, // 14: jmp    16
    0x0011, // 15: jmp    17
    0x0091, // 16: jmp    y--, 17
            //     .wrap_target
    0xa0c2, // 17: mov    isr, y
    0x8000, // 18: push   noblock
    0x60c2, // 19: out    isr, 2
    0x4002, // 20: in     pins, 2
    0xa0e6, // 21: mov    osr, isr
    0xa0a6, // 22: mov    pc, isr
            //     .wrap
    0xa04a, // 23: mov    y, ~y
    0x0099, // 24: jmp    y--, 25
    0xa04a, // 25: mov    y, ~y
    0x0011, // 26: jmp    17
};

#if !PICO_NO_HARDWARE
static const struct pio_program quadrature_encoder_program = {
    .instructions = quadrature_encoder_program_instructions,
    .length = 27,
    .origin = 0,
    .pio_version = quadrature_encoder_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config quadrature_encoder_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + quadrature_encoder_wrap_target, offset + quadrature_encoder_wrap);
    return c;
}

#include "hardware/clocks.h"
#include "hardware/gpio.h"
// max_step_rate is used to lower the clock of the state machine to save power
// if the application doesn't require a very high sampling rate. Passing zero
// will set the clock to the maximum.
//
// NOTE (brain UI): unlike the upstream example this helper does NOT enable
// pull-ups on the pins — the encoder common is driven high, so the sketch
// configures pull-downs before calling this.
static inline void quadrature_encoder_program_init(PIO pio, uint sm, uint pin, int max_step_rate)
{
    pio_sm_set_consecutive_pindirs(pio, sm, pin, 2, false);
    pio_sm_config c = quadrature_encoder_program_get_default_config(0);
    sm_config_set_in_pins(&c, pin); // for WAIT, IN
    sm_config_set_jmp_pin(&c, pin); // for JMP
    // shift to left, autopull disabled
    sm_config_set_in_shift(&c, false, false, 32);
    // don't join FIFO's
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_NONE);
    // passing "0" as the sample frequency,
    if (max_step_rate == 0) {
        sm_config_set_clkdiv(&c, 1.0);
    } else {
        // one state machine loop takes at most 10 cycles
        float div = (float)clock_get_hz(clk_sys) / (10 * max_step_rate);
        sm_config_set_clkdiv(&c, div);
    }
    pio_sm_init(pio, sm, 0, &c);
    pio_sm_set_enabled(pio, sm, true);
}
// When the state machine is running, it keeps trying to write the current
// count to the RX FIFO. To read the current count, drain the FIFO first and
// then wait for the next (guaranteed fresh) sample.
static inline int32_t quadrature_encoder_get_count(PIO pio, uint sm)
{
    uint ret;
    int n;
    // if the FIFO has N entries, we fetch them to drain the FIFO,
    // plus one entry which will be guaranteed to not be stale
    n = pio_sm_get_rx_fifo_level(pio, sm) + 1;
    while (n > 0) {
        ret = pio_sm_get_blocking(pio, sm);
        n--;
    }
    return (int32_t)ret;
}

#endif

